// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackyAPI.Data;

#nullable disable

namespace PackyAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PackyAPI.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quebec",
                            shortname = "QC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ontario",
                            shortname = "ON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "New Brunswick",
                            shortname = "NB"
                        },
                        new
                        {
                            Id = 4,
                            Name = "British Columbia",
                            shortname = "BC"
                        });
                });

            modelBuilder.Entity("PackyAPI.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "QCb",
                            CountryId = 1,
                            Name = "The Quebec Hotel",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "ONt",
                            CountryId = 2,
                            Name = "The Ontario Hotel",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "NBs",
                            CountryId = 3,
                            Name = "The Brunswick Hotel",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "BCo",
                            CountryId = 4,
                            Name = "The Vancouver Hotel",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("PackyAPI.Data.Hotel", b =>
                {
                    b.HasOne("PackyAPI.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
